#ifndef MOVES_H
#define MOVES_H

//#include <QString>
#include <string>
#include <unordered_map>

const std::unordered_map<std::string, double> moves = {
    {"Pound", 1},
    {"Karate Chop", 1},
    {"Double Slap", 0.85},
    {"Comet Punch", 0.85},
    {"Mega Punch", 0.85},
    {"Pay Day", 1},
    {"Fire Punch", 1},
    {"Ice Punch", 1},
    {"Thunder Punch", 1},
    {"Scratch", 1},
    {"Vise Grip", 1},
    {"Guillotine", 0.3},
    {"Razor Wind", 1},
    {"Swords Dance", 2},
    {"Cut", 0.95},
    {"Gust", 1},
    {"Wing Attack", 1},
    {"Whirlwind", 2},
    {"Fly", 0.95},
    {"Bind", 0.85},
    {"Slam", 0.75},
    {"Vine Whip", 1},
    {"Stomp", 1},
    {"Double Kick", 1},
    {"Mega Kick", 0.75},
    {"Jump Kick", 0.95},
    {"Rolling Kick", 0.85},
    {"Sand Attack", 1},
    {"Headbutt", 1},
    {"Horn Attack", 1},
    {"Fury Attack", 0.85},
    {"Horn Drill", 0.3},
    {"Tackle", 1},
    {"Body Slam", 1},
    {"Wrap", 0.9},
    {"Take Down", 0.85},
    {"Thrash", 1},
    {"Double-Edge", 1},
    {"Tail Whip", 1},
    {"Poison Sting", 1},
    {"Twineedle", 1},
    {"Pin Missile", 0.95},
    {"Leer", 1},
    {"Bite", 1},
    {"Growl", 1},
    {"Roar", 2},
    {"Sing", 0.55},
    {"Supersonic", 0.55},
    {"Sonic Boom", 0.9},
    {"Disable", 1},
    {"Acid", 1},
    {"Ember", 1},
    {"Flamethrower", 1},
    {"Mist", 2},
    {"Water Gun", 1},
    {"Hydro Pump", 0.8},
    {"Surf", 1},
    {"Ice Beam", 1},
    {"Blizzard", 0.7},
    {"Psybeam", 1},
    {"Bubble Beam", 1},
    {"Aurora Beam", 1},
    {"Hyper Beam", 0.9},
    {"Peck", 1},
    {"Drill Peck", 1},
    {"Submission", 0.8},
    {"Low Kick", 1},
    {"Counter", 1},
    {"Seismic Toss", 1},
    {"Strength", 1},
    {"Absorb", 1},
    {"Mega Drain", 1},
    {"Leech Seed", 0.9},
    {"Growth", 2},
    {"Razor Leaf", 0.95},
    {"Solar Beam", 1},
    {"Poison Powder", 0.75},
    {"Stun Spore", 0.75},
    {"Sleep Powder", 0.75},
    {"Petal Dance", 1},
    {"String Shot", 0.95},
    {"Dragon Rage", 1},
    {"Fire Spin", 0.85},
    {"Thunder Shock", 1},
    {"Thunderbolt", 1},
    {"Thunder Wave", 0.9},
    {"Thunder", 0.7},
    {"Rock Throw", 0.9},
    {"Earthquake", 1},
    {"Fissure", 0.3},
    {"Dig", 1},
    {"Toxic", 0.9},
    {"Confusion", 1},
    {"Psychic", 1},
    {"Hypnosis", 0.6},
    {"Meditate", 2},
    {"Agility", 2},
    {"Quick Attack", 1},
    {"Rage", 1},
    {"Teleport", 2},
    {"Night Shade", 1},
    {"Mimic", 2},
    {"Screech", 0.85},
    {"Double Team", 2},
    {"Recover", 2},
    {"Harden", 2},
    {"Minimize", 2},
    {"Smokescreen", 1},
    {"Confuse Ray", 1},
    {"Withdraw", 2},
    {"Defense Curl", 2},
    {"Barrier", 2},
    {"Light Screen", 2},
    {"Haze", 2},
    {"Reflect", 2},
    {"Focus Energy", 2},
    {"Bide", 2},
    {"Metronome", 2},
    {"Mirror Move", 2},
    {"Self-Destruct", 1},
    {"Egg Bomb", 0.75},
    {"Lick", 1},
    {"Smog", 0.7},
    {"Sludge", 1},
    {"Bone Club", 0.85},
    {"Fire Blast", 0.85},
    {"Waterfall", 1},
    {"Clamp", 0.85},
    {"Swift", 2},
    {"Skull Bash", 1},
    {"Spike Cannon", 1},
    {"Constrict", 1},
    {"Amnesia", 2},
    {"Kinesis", 0.8},
    {"Soft-Boiled", 2},
    {"High Jump Kick", 0.9},
    {"Glare", 1},
    {"Dream Eater", 1},
    {"Poison Gas", 0.9},
    {"Barrage", 0.85},
    {"Leech Life", 1},
    {"Lovely Kiss", 0.75},
    {"Sky Attack", 0.9},
    {"Transform", 2},
    {"Bubble", 1},
    {"Dizzy Punch", 1},
    {"Spore", 1},
    {"Flash", 1},
    {"Psywave", 1},
    {"Splash", 2},
    {"Acid Armor", 2},
    {"Crabhammer", 0.9},
    {"Explosion", 1},
    {"Fury Swipes", 0.8},
    {"Bonemerang", 0.9},
    {"Rest", 2},
    {"Rock Slide", 0.9},
    {"Hyper Fang", 0.9},
    {"Sharpen", 2},
    {"Conversion", 2},
    {"Tri Attack", 1},
    {"Super Fang", 0.9},
    {"Slash", 1},
    {"Substitute", 2},
    {"Struggle", 2},
    {"Sketch", 2},
    {"Triple Kick", 0.9},
    {"Thief", 1},
    {"Spider Web", 2},
    {"Mind Reader", 2},
    {"Nightmare", 1},
    {"Flame Wheel", 1},
    {"Snore", 1},
    {"Curse", 2},
    {"Flail", 1},
    {"Conversion 2", 2},
    {"Aeroblast", 0.95},
    {"Cotton Spore", 1},
    {"Reversal", 1},
    {"Spite", 1},
    {"Powder Snow", 1},
    {"Protect", 2},
    {"Mach Punch", 1},
    {"Scary Face", 1},
    {"Feint Attack", 2},
    {"Sweet Kiss", 0.75},
    {"Belly Drum", 2},
    {"Sludge Bomb", 1},
    {"Mud-Slap", 1},
    {"Octazooka", 0.85},
    {"Spikes", 2},
    {"Zap Cannon", 0.5},
    {"Foresight", 2},
    {"Destiny Bond", 2},
    {"Perish Song", 2},
    {"Icy Wind", 0.95},
    {"Detect", 2},
    {"Bone Rush", 0.9},
    {"Lock-On", 2},
    {"Outrage", 1},
    {"Sandstorm", 2},
    {"Giga Drain", 1},
    {"Endure", 2},
    {"Charm", 1},
    {"Rollout", 0.9},
    {"False Swipe", 1},
    {"Swagger", 0.85},
    {"Milk Drink", 2},
    {"Spark", 1},
    {"Fury Cutter", 0.95},
    {"Steel Wing", 0.9},
    {"Mean Look", 2},
    {"Attract", 1},
    {"Sleep Talk", 2},
    {"Heal Bell", 2},
    {"Return", 1},
    {"Present", 0.9},
    {"Frustration", 1},
    {"Safeguard", 2},
    {"Pain Split", 2},
    {"Sacred Fire", 0.95},
    {"Magnitude", 1},
    {"Dynamic Punch", 0.5},
    {"Megahorn", 0.85},
    {"Dragon Breath", 1},
    {"Baton Pass", 2},
    {"Encore", 1},
    {"Pursuit", 1},
    {"Rapid Spin", 1},
    {"Sweet Scent", 1},
    {"Iron Tail", 0.75},
    {"Metal Claw", 0.95},
    {"Vital Throw", 2},
    {"Morning Sun", 2},
    {"Synthesis", 2},
    {"Moonlight", 2},
    {"Hidden Power", 1},
    {"Cross Chop", 0.8},
    {"Twister", 1},
    {"Rain Dance", 2},
    {"Sunny Day", 2},
    {"Crunch", 1},
    {"Mirror Coat", 1},
    {"Psych Up", 2},
    {"Extreme Speed", 1},
    {"Ancient Power", 1},
    {"Shadow Ball", 1},
    {"Future Sight", 1},
    {"Rock Smash", 1},
    {"Whirlpool", 0.85},
    {"Beat Up", 1},
    {"Fake Out", 1},
    {"Uproar", 1},
    {"Stockpile", 2},
    {"Spit Up", 1},
    {"Swallow", 2},
    {"Heat Wave", 0.9},
    {"Hail", 2},
    {"Torment", 1},
    {"Flatter", 1},
    {"Will-O-Wisp", 0.85},
    {"Memento", 1},
    {"Facade", 1},
    {"Focus Punch", 1},
    {"Smelling Salts", 1},
    {"Follow Me", 2},
    {"Nature Power", 2},
    {"Charge", 2},
    {"Taunt", 1},
    {"Helping Hand", 2},
    {"Trick", 1},
    {"Role Play", 2},
    {"Wish", 2},
    {"Assist", 2},
    {"Ingrain", 2},
    {"Superpower", 1},
    {"Magic Coat", 2},
    {"Recycle", 2},
    {"Revenge", 1},
    {"Brick Break", 1},
    {"Yawn", 2},
    {"Knock Off", 1},
    {"Endeavor", 1},
    {"Eruption", 1},
    {"Skill Swap", 2},
    {"Imprison", 2},
    {"Refresh", 2},
    {"Grudge", 2},
    {"Snatch", 2},
    {"Secret Power", 1},
    {"Dive", 1},
    {"Arm Thrust", 1},
    {"Camouflage", 2},
    {"Tail Glow", 2},
    {"Luster Purge", 1},
    {"Mist Ball", 1},
    {"Feather Dance", 1},
    {"Teeter Dance", 1},
    {"Blaze Kick", 0.9},
    {"Mud Sport", 2},
    {"Ice Ball", 0.9},
    {"Needle Arm", 1},
    {"Slack Off", 2},
    {"Hyper Voice", 1},
    {"Poison Fang", 1},
    {"Crush Claw", 0.95},
    {"Blast Burn", 0.9},
    {"Hydro Cannon", 0.9},
    {"Meteor Mash", 0.9},
    {"Astonish", 1},
    {"Weather Ball", 1},
    {"Aromatherapy", 2},
    {"Fake Tears", 1},
    {"Air Cutter", 0.95},
    {"Overheat", 0.9},
    {"Odor Sleuth", 2},
    {"Rock Tomb", 0.95},
    {"Silver Wind", 1},
    {"Metal Sound", 0.85},
    {"Grass Whistle", 0.55},
    {"Tickle", 1},
    {"Cosmic Power", 2},
    {"Water Spout", 1},
    {"Signal Beam", 1},
    {"Shadow Punch", 2},
    {"Extrasensory", 1},
    {"Sky Uppercut", 0.9},
    {"Sand Tomb", 0.85},
    {"Sheer Cold", 0.3},
    {"Muddy Water", 0.85},
    {"Bullet Seed", 1},
    {"Aerial Ace", 2},
    {"Icicle Spear", 1},
    {"Iron Defense", 2},
    {"Block", 2},
    {"Howl", 2},
    {"Dragon Claw", 1},
    {"Frenzy Plant", 0.9},
    {"Bulk Up", 2},
    {"Bounce", 0.85},
    {"Mud Shot", 0.95},
    {"Poison Tail", 1},
    {"Covet", 1},
    {"Volt Tackle", 1},
    {"Magical Leaf", 2},
    {"Water Sport", 2},
    {"Calm Mind", 2},
    {"Leaf Blade", 1},
    {"Dragon Dance", 2},
    {"Rock Blast", 0.9},
    {"Shock Wave", 2},
    {"Water Pulse", 1},
    {"Doom Desire", 1},
    {"Psycho Boost", 0.9},
    {"Roost", 2},
    {"Gravity", 2},
    {"Miracle Eye", 2},
    {"Wake-Up Slap", 1},
    {"Hammer Arm", 0.9},
    {"Gyro Ball", 1},
    {"Healing Wish", 2},
    {"Brine", 1},
    {"Natural Gift", 1},
    {"Feint", 1},
    {"Pluck", 1},
    {"Tailwind", 2},
    {"Acupressure", 2},
    {"Metal Burst", 1},
    {"U-turn", 1},
    {"Close Combat", 1},
    {"Payback", 1},
    {"Assurance", 1},
    {"Embargo", 1},
    {"Fling", 1},
    {"Psycho Shift", 1},
    {"Trump Card", 2},
    {"Heal Block", 1},
    {"Wring Out", 1},
    {"Power Trick", 2},
    {"Gastro Acid", 1},
    {"Lucky Chant", 2},
    {"Me First", 2},
    {"Copycat", 2},
    {"Power Swap", 2},
    {"Guard Swap", 2},
    {"Punishment", 1},
    {"Last Resort", 1},
    {"Worry Seed", 1},
    {"Sucker Punch", 1},
    {"Toxic Spikes", 2},
    {"Heart Swap", 2},
    {"Aqua Ring", 2},
    {"Magnet Rise", 2},
    {"Flare Blitz", 1},
    {"Force Palm", 1},
    {"Aura Sphere", 2},
    {"Rock Polish", 2},
    {"Poison Jab", 1},
    {"Dark Pulse", 1},
    {"Night Slash", 1},
    {"Aqua Tail", 0.9},
    {"Seed Bomb", 1},
    {"Air Slash", 0.95},
    {"X-Scissor", 1},
    {"Bug Buzz", 1},
    {"Dragon Pulse", 1},
    {"Dragon Rush", 0.75},
    {"Power Gem", 1},
    {"Drain Punch", 1},
    {"Vacuum Wave", 1},
    {"Focus Blast", 0.7},
    {"Energy Ball", 1},
    {"Brave Bird", 1},
    {"Earth Power", 1},
    {"Switcheroo", 1},
    {"Giga Impact", 0.9},
    {"Nasty Plot", 2},
    {"Bullet Punch", 1},
    {"Avalanche", 1},
    {"Ice Shard", 1},
    {"Shadow Claw", 1},
    {"Thunder Fang", 0.95},
    {"Ice Fang", 0.95},
    {"Fire Fang", 0.95},
    {"Shadow Sneak", 1},
    {"Mud Bomb", 0.85},
    {"Psycho Cut", 1},
    {"Zen Headbutt", 0.9},
    {"Mirror Shot", 0.85},
    {"Flash Cannon", 1},
    {"Rock Climb", 0.85},
    {"Defog", 2},
    {"Trick Room", 2},
    {"Draco Meteor", 0.9},
    {"Discharge", 1},
    {"Lava Plume", 1},
    {"Leaf Storm", 0.9},
    {"Power Whip", 0.85},
    {"Rock Wrecker", 0.9},
    {"Cross Poison", 1},
    {"Gunk Shot", 0.8},
    {"Iron Head", 1},
    {"Magnet Bomb", 2},
    {"Stone Edge", 0.8},
    {"Captivate", 1},
    {"Stealth Rock", 2},
    {"Grass Knot", 1},
    {"Chatter", 1},
    {"Judgment", 1},
    {"Bug Bite", 1},
    {"Charge Beam", 0.9},
    {"Wood Hammer", 1},
    {"Aqua Jet", 1},
    {"Attack Order", 1},
    {"Defend Order", 2},
    {"Heal Order", 2},
    {"Head Smash", 0.8},
    {"Double Hit", 0.9},
    {"Roar of Time", 0.9},
    {"Spacial Rend", 0.95},
    {"Lunar Dance", 2},
    {"Crush Grip", 1},
    {"Magma Storm", 0.75},
    {"Dark Void", 0.5},
    {"Seed Flare", 0.85},
    {"Ominous Wind", 1},
    {"Shadow Force", 1},
    {"Hone Claws", 2},
    {"Wide Guard", 2},
    {"Guard Split", 2},
    {"Power Split", 2},
    {"Wonder Room", 2},
    {"Psyshock", 1},
    {"Venoshock", 1},
    {"Autotomize", 2},
    {"Rage Powder", 2},
    {"Telekinesis", 2},
    {"Magic Room", 2},
    {"Smack Down", 1},
    {"Storm Throw", 1},
    {"Flame Burst", 1},
    {"Sludge Wave", 1},
    {"Quiver Dance", 2},
    {"Heavy Slam", 1},
    {"Synchronoise", 1},
    {"Electro Ball", 1},
    {"Soak", 1},
    {"Flame Charge", 1},
    {"Coil", 2},
    {"Low Sweep", 1},
    {"Acid Spray", 1},
    {"Foul Play", 1},
    {"Simple Beam", 1},
    {"Entrainment", 1},
    {"After You", 2},
    {"Round", 1},
    {"Echoed Voice", 1},
    {"Chip Away", 1},
    {"Clear Smog", 2},
    {"Stored Power", 1},
    {"Quick Guard", 2},
    {"Ally Switch", 2},
    {"Scald", 1},
    {"Shell Smash", 2},
    {"Heal Pulse", 2},
    {"Hex", 1},
    {"Sky Drop", 1},
    {"Shift Gear", 2},
    {"Circle Throw", 0.9},
    {"Incinerate", 1},
    {"Quash", 1},
    {"Acrobatics", 1},
    {"Reflect Type", 2},
    {"Retaliate", 1},
    {"Final Gambit", 1},
    {"Bestow", 2},
    {"Inferno", 0.5},
    {"Water Pledge", 1},
    {"Fire Pledge", 1},
    {"Grass Pledge", 1},
    {"Volt Switch", 1},
    {"Struggle Bug", 1},
    {"Bulldoze", 1},
    {"Frost Breath", 0.9},
    {"Dragon Tail", 0.9},
    {"Work Up", 2},
    {"Electroweb", 0.95},
    {"Wild Charge", 1},
    {"Drill Run", 0.95},
    {"Dual Chop", 0.9},
    {"Heart Stamp", 1},
    {"Horn Leech", 1},
    {"Sacred Sword", 1},
    {"Razor Shell", 0.95},
    {"Heat Crash", 1},
    {"Leaf Tornado", 0.9},
    {"Steamroller", 1},
    {"Cotton Guard", 2},
    {"Night Daze", 0.95},
    {"Psystrike", 1},
    {"Tail Slap", 0.85},
    {"Hurricane", 0.7},
    {"Head Charge", 1},
    {"Gear Grind", 0.85},
    {"Searing Shot", 1},
    {"Techno Blast", 1},
    {"Relic Song", 1},
    {"Secret Sword", 1},
    {"Glaciate", 0.95},
    {"Bolt Strike", 0.85},
    {"Blue Flare", 0.85},
    {"Fiery Dance", 1},
    {"Freeze Shock", 0.9},
    {"Ice Burn", 0.9},
    {"Snarl", 0.95},
    {"Icicle Crash", 0.9},
    {"V-create", 0.95},
    {"Fusion Flare", 1},
    {"Fusion Bolt", 1},
    {"Flying Press", 0.95},
    {"Mat Block", 2},
    {"Belch", 0.9},
    {"Rototiller", 2},
    {"Sticky Web", 2},
    {"Fell Stinger", 1},
    {"Phantom Force", 1},
    {"Trick-or-Treat", 1},
    {"Noble Roar", 1},
    {"Ion Deluge", 2},
    {"Parabolic Charge", 1},
    {"Forest's Curse", 1},
    {"Petal Blizzard", 1},
    {"Freeze-Dry", 1},
    {"Disarming Voice", 2},
    {"Parting Shot", 1},
    {"Topsy-Turvy", 2},
    {"Draining Kiss", 1},
    {"Crafty Shield", 2},
    {"Flower Shield", 2},
    {"Grassy Terrain", 2},
    {"Misty Terrain", 2},
    {"Electrify", 2},
    {"Play Rough", 0.9},
    {"Fairy Wind", 1},
    {"Moonblast", 1},
    {"Boomburst", 1},
    {"Fairy Lock", 2},
    {"King's Shield", 2},
    {"Play Nice", 2},
    {"Confide", 2},
    {"Diamond Storm", 0.95},
    {"Steam Eruption", 0.95},
    {"Hyperspace Hole", 2},
    {"Water Shuriken", 1},
    {"Mystical Fire", 1},
    {"Spiky Shield", 2},
    {"Aromatic Mist", 2},
    {"Eerie Impulse", 1},
    {"Venom Drench", 1},
    {"Powder", 1},
    {"Geomancy", 2},
    {"Magnetic Flux", 2},
    {"Happy Hour", 2},
    {"Electric Terrain", 2},
    {"Dazzling Gleam", 1},
    {"Celebrate", 2},
    {"Hold Hands", 2},
    {"Baby-Doll Eyes", 1},
    {"Nuzzle", 1},
    {"Hold Back", 1},
    {"Infestation", 1},
    {"Power-Up Punch", 1},
    {"Oblivion Wing", 1},
    {"Thousand Arrows", 1},
    {"Thousand Waves", 1},
    {"Land's Wrath", 1},
    {"Light of Ruin", 0.9},
    {"Origin Pulse", 0.85},
    {"Precipice Blades", 0.85},
    {"Dragon Ascent", 1},
    {"Hyperspace Fury", 2},
    {"Breakneck Blitz", 2},
    {"All-Out Pummeling", 2},
    {"Supersonic Skystrike", 2},
    {"Acid Downpour", 2},
    {"Tectonic Rage", 2},
    {"Continental Crush", 2},
    {"Savage Spin-Out", 2},
    {"Never-Ending Nightmare", 2},
    {"Corkscrew Crash", 2},
    {"Inferno Overdrive", 2},
    {"Hydro Vortex", 2},
    {"Bloom Doom", 2},
    {"Gigavolt Havoc", 2},
    {"Shattered Psyche", 2},
    {"Subzero Slammer", 2},
    {"Devastating Drake", 2},
    {"Black Hole Eclipse", 2},
    {"Twinkle Tackle", 2},
    {"Catastropika", 2},
    {"Shore Up", 2},
    {"First Impression", 1},
    {"Baneful Bunker", 2},
    {"Spirit Shackle", 1},
    {"Darkest Lariat", 1},
    {"Sparkling Aria", 1},
    {"Ice Hammer", 0.9},
    {"Floral Healing", 2},
    {"High Horsepower", 0.95},
    {"Strength Sap", 1},
    {"Solar Blade", 1},
    {"Leafage", 1},
    {"Spotlight", 2},
    {"Toxic Thread", 1},
    {"Laser Focus", 2},
    {"Gear Up", 2},
    {"Throat Chop", 1},
    {"Pollen Puff", 1},
    {"Anchor Shot", 1},
    {"Psychic Terrain", 2},
    {"Lunge", 1},
    {"Fire Lash", 1},
    {"Power Trip", 1},
    {"Burn Up", 1},
    {"Speed Swap", 2},
    {"Smart Strike", 2},
    {"Purify", 2},
    {"Revelation Dance", 1},
    {"Core Enforcer", 1},
    {"Trop Kick", 1},
    {"Instruct", 2},
    {"Beak Blast", 1},
    {"Clanging Scales", 1},
    {"Dragon Hammer", 1},
    {"Brutal Swing", 1},
    {"Aurora Veil", 2},
    {"Sinister Arrow Raid", 2},
    {"Malicious Moonsault", 2},
    {"Oceanic Operetta", 2},
    {"Guardian of Alola", 2},
    {"Soul-Stealing 7-Star Strike", 2},
    {"Stoked Sparksurfer", 2},
    {"Pulverizing Pancake", 2},
    {"Extreme Evoboost", 2},
    {"Genesis Supernova", 2},
    {"Shell Trap", 1},
    {"Fleur Cannon", 0.9},
    {"Psychic Fangs", 1},
    {"Stomping Tantrum", 1},
    {"Shadow Bone", 1},
    {"Accelerock", 1},
    {"Liquidation", 1},
    {"Prismatic Laser", 1},
    {"Spectral Thief", 1},
    {"Sunsteel Strike", 1},
    {"Moongeist Beam", 1},
    {"Tearful Look", 2},
    {"Zing Zap", 1},
    {"Nature's Madness", 0.9},
    {"Multi-Attack", 1},
    {"10.000.000 Volt Thunderbolt", 2},
    {"Mind Blown", 1},
    {"Plasma Fists", 1},
    {"Photon Geyser", 1},
    {"Light That Burns the Sky", 2},
    {"Searing Sunraze Smash", 2},
    {"Menacing Moonraze Maelstrom", 2},
    {"Let's Snuggle Forever", 2},
    {"Splintered Stormshards", 2},
    {"Clangorous Soulblaze", 2},
    {"Zippy Zap", 1},
    {"Splishy Splash", 1},
    {"Floaty Fall", 0.95},
    {"Pika Papow", 2},
    {"Bouncy Bubble", 1},
    {"Buzzy Buzz", 1},
    {"Sizzly Slide", 1},
    {"Glitzy Glow", 0.95},
    {"Baddy Bad", 0.95},
    {"Sappy Seed", 0.9},
    {"Freezy Frost", 0.9},
    {"Sparkly Swirl", 0.85},
    {"Veevee Volley", 2},
    {"Double Iron Bash", 1},
    {"Max Guard", 2},
    {"Dynamax Cannon", 1},
    {"Snipe Shot", 1},
    {"Jaw Lock", 1},
    {"Stuff Cheeks", 2},
    {"No Retreat", 2},
    {"Tar Shot", 1},
    {"Magic Powder", 1},
    {"Dragon Darts", 1},
    {"Teatime", 2},
    {"Octolock", 1},
    {"Bolt Beak", 1},
    {"Fishious Rend", 1},
    {"Court Change", 1},
    {"Max Flare", 2},
    {"Max Flutterby", 2},
    {"Max Lightning", 2},
    {"Max Strike", 2},
    {"Max Knuckle", 2},
    {"Max Phantasm", 2},
    {"Max Hailstorm", 2},
    {"Max Ooze", 2},
    {"Max Geyser", 2},
    {"Max Airstream", 2},
    {"Max Starfall", 2},
    {"Max Wyrmwind", 2},
    {"Max Mindstorm", 2},
    {"Max Rockfall", 2},
    {"Max Quake", 2},
    {"Max Darkness", 2},
    {"Max Overgrowth", 2},
    {"Max Steelspike", 2},
    {"Clangorous Soul", 2},
    {"Body Press", 1},
    {"Decorate", 2},
    {"Drum Beating", 1},
    {"Snap Trap", 1},
    {"Pyro Ball", 0.9},
    {"Behemoth Blade", 1},
    {"Behemoth Bash", 1},
    {"Aura Wheel", 1},
    {"Breaking Swipe", 1},
    {"Branch Poke", 1},
    {"Overdrive", 1},
    {"Apple Acid", 1},
    {"Grav Apple", 1},
    {"Spirit Break", 1},
    {"Strange Steam", 0.95},
    {"Life Dew", 2},
    {"Obstruct", 1},
    {"False Surrender", 2},
    {"Meteor Assault", 1},
    {"Eternabeam", 0.9},
    {"Steel Beam", 0.95},
    {"Expanding Force", 1},
    {"Steel Roller", 1},
    {"Scale Shot", 0.9},
    {"Meteor Beam", 0.9},
    {"Shell Side Arm", 1},
    {"Misty Explosion", 1},
    {"Grassy Glide", 1},
    {"Rising Voltage", 1},
    {"Terrain Pulse", 1},
    {"Skitter Smack", 0.9},
    {"Burning Jealousy", 1},
    {"Lash Out", 1},
    {"Poltergeist", 0.9},
    {"Corrosive Gas", 1},
    {"Coaching", 2},
    {"Flip Turn", 1},
    {"Triple Axel", 0.9},
    {"Dual Wingbeat", 0.9},
    {"Scorching Sands", 1},
    {"Jungle Healing", 2},
    {"Wicked Blow", 1},
    {"Surging Strikes", 1},
    {"Thunder Cage", 0.9},
    {"Dragon Energy", 1},
    {"Freezing Glare", 1},
    {"Fiery Wrath", 1},
    {"Thunderous Kick", 1},
    {"Glacial Lance", 1},
    {"Astral Barrage", 1},
    {"Eerie Spell", 1},
    {"Dire Claw", 1},
    {"Psyshield Bash", 0.9},
    {"Power Shift", 2},
    {"Stone Axe", 0.9},
    {"Springtide Storm", 0.8},
    {"Mystical Power", 0.9},
    {"Raging Fury", 1},
    {"Wave Crash", 1},
    {"Chloroblast", 0.95},
    {"Mountain Gale", 0.85},
    {"Victory Dance", 2},
    {"Headlong Rush", 1},
    {"Barb Barrage", 1},
    {"Esper Wing", 1},
    {"Bitter Malice", 1},
    {"Shelter", 2},
    {"Triple Arrows", 1},
    {"Infernal Parade", 1},
    {"Ceaseless Edge", 0.9},
    {"Bleakwind Storm", 0.8},
    {"Wildbolt Storm", 0.8},
    {"Sandsear Storm", 0.8},
    {"Lunar Blessing", 2},
    {"Take Heart", 2},
    {"Tera Blast", 1},
    {"Silk Trap", 2},
    {"Axe Kick", 0.9},
    {"Last Respects", 1},
    {"Lumina Crash", 1},
    {"Order Up", 1},
    {"Jet Punch", 1},
    {"Spicy Extract", 2},
    {"Spin Out", 1},
    {"Population Bomb", 0.9},
    {"Ice Spinner", 1},
    {"Glaive Rush", 1},
    {"Revival Blessing", 2},
    {"Salt Cure", 1},
    {"Triple Dive", 0.95},
    {"Mortal Spin", 1},
    {"Doodle", 1},
    {"Fillet Away", 2},
    {"Kowtow Cleave", 2},
    {"Flower Trick", 2},
    {"Torch Song", 1},
    {"Aqua Step", 1},
    {"Raging Bull", 1},
    {"Make It Rain", 1},
    {"Psyblade", 1},
    {"Hydro Steam", 1},
    {"Ruination", 0.9},
    {"Collision Course", 1},
    {"Electro Drift", 1},
    {"Shed Tail", 2},
    {"Chilly Reception", 2},
    {"Tidy Up", 2},
    {"Snowscape", 2},
    {"Pounce", 1},
    {"Trailblaze", 1},
    {"Chilling Water", 1},
    {"Hyper Drill", 1},
    {"Twin Beam", 1},
    {"Rage Fist", 1},
    {"Armor Cannon", 1},
    {"Bitter Blade", 1},
    {"Double Shock", 1},
    {"Gigaton Hammer", 1},
    {"Comeuppance", 1},
    {"Aqua Cutter", 1},
    {"Blazing Torque", 1},
    {"Wicked Torque", 1},
    {"Noxious Torque", 1},
    {"Combat Torque", 1},
    {"Magical Torque", 1},
    {"Blood Moon", 1},
    {"Matcha Gotcha", 0.9},
    {"Syrup Bomb", 0.85},
    {"Ivy Cudgel", 1},
    {"Electro Shot", 1},
    {"Tera Starstorm", 1},
    {"Fickle Beam", 1},
    {"Burning Bulwark", 2},
    {"Thunderclap", 1},
    {"Mighty Cleave", 1},
    {"Tachyon Cutter", 2},
    {"Hard Press", 1},
    {"Dragon Cheer", 2},
    {"Alluring Voice", 1},
    {"Temper Flare", 1},
    {"Supercell Slam", 0.95},
    {"Psychic Noise", 1},
    {"Upper Hand", 1},
    {"Malignant Chain", 1},
};

#endif // MOVES_H
